plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-ccs-computing.github.io
baseurl: "/F25-1A"

course: "CMPTGCS 1A"
qtr: "F25"
instructor: "Richert Wang"
quarter: "Fall 2025"
piazza_url:
gauchospace_course_page:
gradescope_class_url: https://www.gradescope.com/

github_url: https://github.com/ucsb-ccs-computing/F25-1A

start_week: 1
start_date: 2025-09-28 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

cal_dates: >                                                                    
  [                                                                            
    {"label":"Veterans Day", "date":"2025-11-11" },
    {"label":"Thanksgiving", "date":"2025-11-27" },
    {"label":"Thanksgiving", "date":"2025-11-28" },
    {"label":"F25 instruction ends", "date":"2025-12-05" },
    {"label":"F25 qtr ends", "date":"2025-12-12" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  cs16:
    output: true
    permalink: /cs16/:path/
    last_before: false
  cs24:
    output: true
    permalink: /cs24/:path/
    last_before: false
  cs32:
    output: true
    permalink: /cs32/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
